class_names = [
    "aloo baigan",
    "aloo gobi",
    "aloo paratha",
    "aloo pat gobi",
    "athirasam",
    "bhel puri",
    "bread",
    "butter masala paneer",
    "capati",
    "chana shag",
    "channa dal masala",
    "chicken beryani",
    "chicken makhani",
    "chole (curried chickpeas)",
    "dhokla",
    "dosai",
    "indian mattar paneer",
    "indian paneer tikka",
    "indian tandoori wrap",
    "indian thalipith",
    "khichdi",
    "koftay",
    "lamb madras curry",
    "lapsi (sweet bulgur)",
    "mughlai paratha",
    "onion pakoda",
    "orange lentils",
    "palak paneer",
    "papadom",
    "puliyogre",
    "punjabi curry with pakora",
    "rajmah",
    "samosa - meat and veg",
    "shev dahi batata puri",
    "shimla mirch aloo",
    "spicy indian rice",
    "string hoppers (idiyapam)",
    "tomato chicken",
    "uttapam",
    "vegetable biryani",
]
l1 = [
    "indian thalipith",
    "papadom",
    "rajmah",
    "bhel puri",
    "dosai",
    "khichdi",
    "koftay",
    "capati",
    "curry",
    "indian paneer tikka",
    "bread",
    "mooli paratha",
    "chicken makhani",
    "vegetable biryani",
    "aloo paratha",
    "onion pakoda",
    "vegetable balti",
    "chicken beryani",
    "cooked chickpeas",
    "orange lentils",
    "puliyogre",
    "mughlai paratha",
    "uttapam",
    "mulligatawny soup",
    "athirasam",
    "aloo baigan",
    "indian - kalay chany",
    "chana shag",
    "chakodi",
    "vegetable jhalfrezi",
    "sarevda-papdi",
    "tomato chicken",
    "akbari kofta",
    "chole (curried chickpeas)",
    "palak paneer",
    "lamb madras curry",
    "channa dal masala",
    "cheese",
    "mutton / lamb biryani",
    "banana leaf rice",
    "lapsi (sweet bulgur)",
    "dhokla",
    "indian mattar paneer",
    "shimla mirch aloo",
    "majjige hulli",
    "butter masala paneer",
    "food indian stew",
    "hing spice",
    "indian tandoori wrap",
    "sardine paratel",
    "aladdin food",
    "spicy indian rice",
    "samosa - meat and veg",
    "aloo gobi",
    "buffet plate - extra chicken",
    "shev dahi batata puri",
    "punjabi curry with pakora",
    "mr. kebab beef biryani",
    "aloo pat gobi",
    "aloo baigan cooked vegitable",
    "string hoppers (idiyapam)",
    "aloo gobi masala internet",
]